name: on push github actions
on:
  push:
    branches:
      - "main"

jobs:
  print-stuff-from-job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, from job 1 world!"

  print-stuff-from-job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, from job 2 world!"
